# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 23:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, help_text='Description for this Boot Action.', max_length=128, null=True)),
                ('command', models.TextField(help_text='Boot Command to render as template.')),
                ('creation_date', models.DateTimeField(auto_now_add=True, help_text='The date and this Boot Command has been added.', null=True, verbose_name='Creation Date')),
                ('change_date', models.DateTimeField(auto_now=True, help_text='The date and time this Boot Command has been changed last.', null=True, verbose_name='Change Date')),
            ],
            options={
                'verbose_name': 'Boot Action Template',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ActionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, help_text='Description for this Boot Action Type.', max_length=128, null=True)),
            ],
            options={
                'verbose_name': 'Boot Action Category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ActionRenderType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, help_text='Description for this Boot Action Type.', max_length=128, null=True)),
                ('command_pre', models.TextField(blank=True, help_text='Commands to render before Action command.', null=True, verbose_name='Pre Action Command')),
                ('command_post', models.TextField(blank=True, help_text='Commands to render after Action command.', null=True, verbose_name='Post Action Command')),
            ],
            options={
                'verbose_name': 'Boot Action Render Type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FallbackAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='Entry ID')),
            ],
            options={
                'verbose_name': 'Boot Fallback Action',
            },
        ),
        migrations.CreateModel(
            name='HostTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(blank=True, help_text='Used to determine Task execution priority.', null=True, verbose_name='Priority')),
                ('action', models.ForeignKey(help_text='Boot Action that should be executed by the Host.', on_delete=django.db.models.deletion.CASCADE, to='bootmgr.Action', verbose_name='Boot Action')),
            ],
            options={
                'verbose_name': 'Host Boot Task',
                'ordering': ['host', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, help_text='Description for this Boot Menu.', max_length=128, null=True)),
            ],
            options={
                'verbose_name': 'Boot Menu',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MenuEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortcut', models.CharField(blank=True, choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D'), ('e', 'E'), ('f', 'F'), ('g', 'G'), ('h', 'H'), ('i', 'I'), ('j', 'J'), ('k', 'K'), ('l', 'L'), ('m', 'M'), ('n', 'N'), ('o', 'O'), ('p', 'P'), ('q', 'Q'), ('r', 'R'), ('s', 'S'), ('t', 'T'), ('u', 'U'), ('v', 'V'), ('w', 'W'), ('x', 'X'), ('y', 'Y'), ('0x01', 'Ctrl-A'), ('0x02', 'Ctrl-B'), ('0x03', 'Ctrl-C'), ('0x04', 'Ctrl-D'), ('0x05', 'Ctrl-E'), ('0x06', 'Ctrl-F'), ('0x07', 'Ctrl-G'), ('0x08', 'Ctrl-H'), ('0x09', 'Ctrl-I'), ('0x0A', 'Ctrl-J'), ('0x0B', 'Ctrl-K'), ('0x0C', 'Ctrl-L'), ('0x0D', 'Ctrl-M'), ('0x0E', 'Ctrl-N'), ('0x0F', 'Ctrl-O'), ('0x10', 'Ctrl-P'), ('0x11', 'Ctrl-Q'), ('0x12', 'Ctrl-R'), ('0x13', 'Ctrl-S'), ('0x14', 'Ctrl-T'), ('0x15', 'Ctrl-U'), ('0x16', 'Ctrl-V'), ('0x17', 'Ctrl-W'), ('0x18', 'Ctrl-X'), ('0x19', 'Ctrl-Y'), ('0x1A', 'Ctrl-Z'), ('0x107e', 'F5'), ('0x127e', 'F6'), ('0x137e', 'F7'), ('0x147e', 'F8'), ('0x157e', 'F9'), ('0x167e', 'F10'), ('0x187e', 'F11'), ('0x197e', 'F12')], max_length=6, null=True, verbose_name='Shortcut Key')),
                ('order', models.SmallIntegerField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField(verbose_name='Entry ID')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Entry Type')),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bootmgr.Menu', verbose_name='Parent Menu')),
            ],
            options={
                'verbose_name': 'Boot Menu Entry',
                'ordering': ['content_type', 'order'],
                'verbose_name_plural': 'Boot Menu Entries',
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True, verbose_name='Site URL')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.CharField(blank=True, help_text='Description for this Boot Site Config.', max_length=128, null=True, verbose_name='Site Description')),
                ('reload_delay', models.PositiveSmallIntegerField(default=10, help_text='Time to wait before reloading the menu after an action has finished without termination.', verbose_name='Reload delay in Seconds')),
                ('reconnect_delay', models.PositiveSmallIntegerField(default=15, help_text='Time to wait before reconnecting if required.', verbose_name='Reconnect delay in Seconds')),
                ('menu_timeout', models.PositiveSmallIntegerField(default=30, help_text='Time to wait before choosing the default menu item. 0=never.', verbose_name='Timeout in Seconds')),
                ('auto_create_hosts', models.BooleanField(default=True, help_text='Automatically create entries for unknown hosts connecting to this site.', verbose_name='Auto Create New Hosts')),
                ('show_menu_fallback', models.BooleanField(default=True, help_text='Show menu before booting fallback entry if existing.', verbose_name='Show Menu before Fallback')),
                ('show_reconnect', models.BooleanField(default=True, help_text='Show reconnect action within defaults in menus.', verbose_name='Show Reconnect')),
                ('auto_reload', models.BooleanField(default=False, help_text='Reload Menu if selected Action has returned successfully. Otherwise exit to BIOS / UEFI.', verbose_name='Auto Reload Menu')),
                ('initial_host_action', models.ForeignKey(blank=True, help_text='Action that will be set as Task for Hosts connecting for the first time.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initial_host_task', to='bootmgr.Action', verbose_name='Initial Host Action Task')),
                ('menu', models.ForeignKey(blank=True, help_text='The Default Boot Menu to show for this Site', null=True, on_delete=django.db.models.deletion.CASCADE, to='bootmgr.Menu', verbose_name='Default Boot Menu')),
                ('timeout_action', models.ForeignKey(blank=True, help_text='Action that will be executed if Host has no Fallback Action.', null=True, on_delete=django.db.models.deletion.CASCADE, to='bootmgr.Action', verbose_name='Default Timeout Action')),
            ],
            options={
                'verbose_name': 'Boot Site Config',
            },
        ),
    ]
