# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 23:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hostdb', '0001_initial'),
        ('bootmgr', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosttask',
            name='host',
            field=models.ForeignKey(help_text='Host that should execute the Boot Action.', on_delete=django.db.models.deletion.CASCADE, to='hostdb.Host'),
        ),
        migrations.AddField(
            model_name='fallbackaction',
            name='action',
            field=models.ForeignKey(help_text='Boot Action that should be executed by the Host if no task exist', on_delete=django.db.models.deletion.CASCADE, to='bootmgr.Action', verbose_name='Fallback Boot Action'),
        ),
        migrations.AddField(
            model_name='fallbackaction',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Entry Type'),
        ),
        migrations.AddField(
            model_name='action',
            name='action_category',
            field=models.ForeignKey(blank=True, help_text='Category helps to filter by.', null=True, on_delete=django.db.models.deletion.CASCADE, to='bootmgr.ActionCategory', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='action',
            name='render_type',
            field=models.ForeignKey(blank=True, help_text='The Action Render Type determines how the Script is rendered', null=True, on_delete=django.db.models.deletion.CASCADE, to='bootmgr.ActionRenderType', verbose_name='Template Render Type'),
        ),
        migrations.AlterUniqueTogether(
            name='fallbackaction',
            unique_together=set([('content_type', 'object_id')]),
        ),
    ]
