from django.apps import AppConfig
from django.conf import settings


class BootManagerAppConfig(AppConfig):
    name = 'netbootmgr.bootmgr'
    label = 'bootmgr'
    verbose_name = "iPXE Boot Manager"

# iPXE Console Width
# MAX_IPXE_WINDOW_WIDTH = 64
MAX_IPXE_WINDOW_WIDTH = 74

# Create new site config when connecting from unknown site
AUTO_CREATE_NEW_SITES = getattr(settings, 'BOOTMGR_AUTO_CREATE_NEW_SITES', True)

# The menu id used when creating new site configs
NEW_SITE_MENU_ID = getattr(settings, 'BOOTMGR_NEW_SITE_MENU_ID', 1)

BOOT_MENU_SHORTCUT_CHOICES = getattr(settings, 'BOOTMGR_BOOT_MENU_SHORTCUT_CHOICES', (
    ('a', 'A'),
    ('b', 'B'),
    ('c', 'C'),
    ('d', 'D'),
    ('e', 'E'),
    ('f', 'F'),
    ('g', 'G'),
    ('h', 'H'),
    ('i', 'I'),
    ('j', 'J'),
    ('k', 'K'),
    ('l', 'L'),
    ('m', 'M'),
    ('n', 'N'),
    ('o', 'O'),
    ('p', 'P'),
    ('q', 'Q'),
    ('r', 'R'),
    ('s', 'S'),
    ('t', 'T'),
    ('u', 'U'),
    ('v', 'V'),
    ('w', 'W'),
    ('x', 'X'),
    ('y', 'Y'),
    ('0x01', 'Ctrl-A'),
    ('0x02', 'Ctrl-B'),
    ('0x03', 'Ctrl-C'),
    ('0x04', 'Ctrl-D'),
    ('0x05', 'Ctrl-E'),
    ('0x06', 'Ctrl-F'),
    ('0x07', 'Ctrl-G'),
    ('0x08', 'Ctrl-H'),
    ('0x09', 'Ctrl-I'),
    ('0x0A', 'Ctrl-J'),
    ('0x0B', 'Ctrl-K'),
    ('0x0C', 'Ctrl-L'),
    ('0x0D', 'Ctrl-M'),
    ('0x0E', 'Ctrl-N'),
    ('0x0F', 'Ctrl-O'),
    ('0x10', 'Ctrl-P'),
    ('0x11', 'Ctrl-Q'),
    ('0x12', 'Ctrl-R'),
    ('0x13', 'Ctrl-S'),
    ('0x14', 'Ctrl-T'),
    ('0x15', 'Ctrl-U'),
    ('0x16', 'Ctrl-V'),
    ('0x17', 'Ctrl-W'),
    ('0x18', 'Ctrl-X'),
    ('0x19', 'Ctrl-Y'),
    ('0x1A', 'Ctrl-Z'),
    ('0x107e', 'F5'),
    ('0x127e', 'F6'),
    ('0x137e', 'F7'),
    ('0x147e', 'F8'),
    ('0x157e', 'F9'),
    ('0x167e', 'F10'),
    ('0x187e', 'F11'),
    ('0x197e', 'F12'),
))

BOOT_MENU_SHORTCUT_CHOICES_DICT = getattr(settings, 'BOOTMGR_BOOT_MENU_SHORTCUT_CHOICES_DICT', {
    'a': 'A',
    'b': 'B',
    'c': 'C',
    'd': 'D',
    'e': 'E',
    'f': 'F',
    'g': 'G',
    'h': 'H',
    'i': 'I',
    'j': 'J',
    'k': 'K',
    'l': 'L',
    'm': 'M',
    'n': 'N',
    'o': 'O',
    'p': 'P',
    'q': 'Q',
    'r': 'R',
    's': 'S',
    't': 'T',
    'u': 'U',
    'v': 'V',
    'w': 'W',
    'x': 'X',
    'y': 'Y',
    '0x01': 'Ctrl-A',
    '0x02': 'Ctrl-B',
    '0x03': 'Ctrl-C',
    '0x04': 'Ctrl-D',
    '0x05': 'Ctrl-E',
    '0x06': 'Ctrl-F',
    '0x07': 'Ctrl-G',
    '0x08': 'Ctrl-H',
    '0x09': 'Ctrl-I',
    '0x0A': 'Ctrl-J',
    '0x0B': 'Ctrl-K',
    '0x0C': 'Ctrl-L',
    '0x0D': 'Ctrl-M',
    '0x0E': 'Ctrl-N',
    '0x0F': 'Ctrl-O',
    '0x10': 'Ctrl-P',
    '0x11': 'Ctrl-Q',
    '0x12': 'Ctrl-R',
    '0x13': 'Ctrl-S',
    '0x14': 'Ctrl-T',
    '0x15': 'Ctrl-U',
    '0x16': 'Ctrl-V',
    '0x17': 'Ctrl-W',
    '0x18': 'Ctrl-X',
    '0x19': 'Ctrl-Y',
    '0x1A': 'Ctrl-Z',
    '0x107e': 'F5',
    '0x127e': 'F6',
    '0x137e': 'F7',
    '0x147e': 'F8',
    '0x157e': 'F9',
    '0x167e': 'F10',
    '0x187e': 'F11',
    '0x197e': 'F12',
})