# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(help_text='Unique Name without blanks', unique=True)),
                ('description', models.CharField(blank=True, help_text='Text describing this Configuration Template', max_length=128, null=True)),
                ('mime_type', models.CharField(choices=[('text/plain', 'plain text'), ('text/html', 'html'), ('text/javascript', 'javascript'), ('text/css', 'css'), ('text/xml', 'xml (text)'), ('application/xml', 'xml (application)'), ('application/json', 'json'), ('text/comma-separated-values', 'csv'), ('application/x-sh', 'shell script')], help_text='MIME Type of the template', max_length=16, verbose_name='MIME Type')),
                ('template', models.TextField(help_text='Template to generate the Configuration from')),
                ('creation_date', models.DateTimeField(auto_now_add=True, help_text='The date when madded.', null=True, verbose_name='Creation Date')),
                ('change_date', models.DateTimeField(auto_now=True, help_text='Last change date.', null=True, verbose_name='Change Date')),
            ],
            options={
                'verbose_name': 'Configuration Template',
            },
        ),
    ]
